//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenLock.languages {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GreenLock {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GreenLock() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GreenLock.languages.GreenLock", typeof(GreenLock).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   장치주소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도난방지알람이 해제되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string antiTheftoff {
            get {
                return ResourceManager.GetString("antiTheftoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도난방지알람이 설정되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string antiThefton {
            get {
                return ResourceManager.GetString("antiThefton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제대로 입력하시오.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string bluetooth_setting_msg {
            get {
                return ResourceManager.GetString("bluetooth_setting_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   블루투스 장치를 켜주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string bluetoothOffMsg {
            get {
                return ResourceManager.GetString("bluetoothOffMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Green lock program update과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ClientUpdatedCheck {
            get {
                return ResourceManager.GetString("ClientUpdatedCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CO2절감(톤)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string co2 {
            get {
                return ResourceManager.GetString("co2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정이 변경되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ConfigChanged {
            get {
                return ResourceManager.GetString("ConfigChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전기료절감액(원)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string cost {
            get {
                return ResourceManager.GetString("cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전기요금(kWh 당)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string electric_Charge {
            get {
                return ResourceManager.GetString("electric_Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   절력값(kW)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string energy {
            get {
                return ResourceManager.GetString("energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실행주의!!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string execution_caution {
            get {
                return ResourceManager.GetString("execution_caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   환경설정에서 장치주소를 입력한 후, 사용해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string execution_caution_msg {
            get {
                return ResourceManager.GetString("execution_caution_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   환경설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string main_Config {
            get {
                return ResourceManager.GetString("main_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   환경설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string main_Config1 {
            get {
                return ResourceManager.GetString("main_Config1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에너지절감량과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string main_Energy {
            get {
                return ResourceManager.GetString("main_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에너지절감량과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string main_Energy1 {
            get {
                return ResourceManager.GetString("main_Energy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보안과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string main_Security {
            get {
                return ResourceManager.GetString("main_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보안과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string main_Security1 {
            get {
                return ResourceManager.GetString("main_Security1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   절전모드 선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string mode {
            get {
                return ResourceManager.GetString("mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모니터 절전과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string monitorMode {
            get {
                return ResourceManager.GetString("monitorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알림사항과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string notice {
            get {
                return ResourceManager.GetString("notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호 분실시 모바일에서 다시 설정하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string notice1 {
            get {
                return ResourceManager.GetString("notice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정이 안될경우 contact@hanscreative.com로 연락주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string notice2 {
            get {
                return ResourceManager.GetString("notice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string pairing {
            get {
                return ResourceManager.GetString("pairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호가 틀렸습니다. \n다시 입력해 주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string passwordError {
            get {
                return ResourceManager.GetString("passwordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모니터+본체 절전과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string pcMode {
            get {
                return ResourceManager.GetString("pcMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에너지절감량(kWh)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string power {
            get {
                return ResourceManager.GetString("power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보안과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string security_worked {
            get {
                return ResourceManager.GetString("security_worked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모니터 절전모드로 변경되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sleepMode_changeMsg0 {
            get {
                return ResourceManager.GetString("sleepMode_changeMsg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모니터+본체 절전모드로 변경되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sleepMode_changeMsg1 {
            get {
                return ResourceManager.GetString("sleepMode_changeMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   절전모드 변경완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sleepMode_changeTitle {
            get {
                return ResourceManager.GetString("sleepMode_changeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   환경설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sses_configuration {
            get {
                return ResourceManager.GetString("sses_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SSES 는 Smart Security and Energy Saving 의 약자로써, PC와 mobile 간의 블루투스 통신을 이용하여 PC 보안 및 에너지를 절약하는 솔루션입니다. \\r\\nPC와 mobile에 맞는 프로그램을 설치하면 SSES 솔루션을 이용하실 수 있습니다. 환경설정에서 mobile 프로그램에 있는 장치주소를 입력한 후, 사용하시기 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sses_introduction {
            get {
                return ResourceManager.GetString("sses_introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amount of Energy Saving과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StringCancel {
            get {
                return ResourceManager.GetString("StringCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StringConfirm {
            get {
                return ResourceManager.GetString("StringConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   환경보호(그루)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string tree {
            get {
                return ResourceManager.GetString("tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   종료시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Uc_TabSecurity_EndDate {
            get {
                return ResourceManager.GetString("Uc_TabSecurity_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GreenLock Lock/Unlock Time Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Uc_TabSecurity_Excel_Sheet_Title_1 {
            get {
                return ResourceManager.GetString("Uc_TabSecurity_Excel_Sheet_Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Daily Lock Unlock Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Uc_TabSecurity_Excel_Sheet_Title_2 {
            get {
                return ResourceManager.GetString("Uc_TabSecurity_Excel_Sheet_Title_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체시간데이터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Uc_TabSecurity_Excel_WorkSheet_Total {
            get {
                return ResourceManager.GetString("Uc_TabSecurity_Excel_WorkSheet_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C:\GreenLock\ExportData과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Uc_TabSecurity_ExcelFilePath {
            get {
                return ResourceManager.GetString("Uc_TabSecurity_ExcelFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그래프로보기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Uc_TabSecurity_Graph {
            get {
                return ResourceManager.GetString("Uc_TabSecurity_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   잠김과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Uc_TabSecurity_Lock {
            get {
                return ResourceManager.GetString("Uc_TabSecurity_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   잠금 또는 해제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Uc_TabSecurity_LockType {
            get {
                return ResourceManager.GetString("Uc_TabSecurity_LockType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Uc_TabSecurity_Regdate {
            get {
                return ResourceManager.GetString("Uc_TabSecurity_Regdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도표로보기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Uc_TabSecurity_Sheet {
            get {
                return ResourceManager.GetString("Uc_TabSecurity_Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시작시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Uc_TabSecurity_StartDate {
            get {
                return ResourceManager.GetString("Uc_TabSecurity_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   합과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Uc_TabSecurity_Sum {
            get {
                return ResourceManager.GetString("Uc_TabSecurity_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   잠김해제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Uc_TabSecurity_Unlock {
            get {
                return ResourceManager.GetString("Uc_TabSecurity_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string userPw {
            get {
                return ResourceManager.GetString("userPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   솔루션소개과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string what_Sses {
            get {
                return ResourceManager.GetString("what_Sses", resourceCulture);
            }
        }
    }
}
