//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenLock.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public string Id { get; set; }
        public string MacAddress { get; set; }
        public System.DateTime RegDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public short LockType { get; set; }
    }
}
